"""
Self-Dev Git Operations (Oturum 25.29 — Evre 2.2)
==================================================

Bot kendi `bot/draft-*` branch'lerinde git işlemleri yapabilir.
- Local: branch create, diff apply, commit (DUSUK risk)
- Remote: push (default KAPALI, flag ile aktive)

KESINLIKLE YASAK (hardcoded):
- main / master / production / develop branch'lerine doğrudan değişiklik
- Force push (--force, --force-with-lease)
- Tag oluşturma
- Submodule değiştirme
- Bot kendi PR'ını merge edemez (Evre 3 kapsamı)

Akış (Neo "draft #5 push" dediğinde):
  1. apply_brief zaten _drafts/5_*.diff yazmıştı (Evre 2.1)
  2. create_draft_branch() → bot/draft-20260430-1
  3. apply_diff_to_branch(branch, draft_path) → gerçek dosya değişir (BU branch'te)
  4. commit_on_branch(branch, "...")
  5. push_branch(branch) → flag kapaliysa local'de kal
  6. (Evre 2.3) gh_pr_create_draft → PR aç

Bu oturumda push KOD HAZIR, FLAG KAPALI. Neo aktive edene kadar local kalır.
"""
from __future__ import annotations
import os
import re
import json
import time
import subprocess
from datetime import datetime
from typing import Optional

from loguru import logger


# ─── Konfigürasyon ──────────────────────────────────────────────────────────

REPO_PATH = "/opt/fermatai" if os.path.isdir("/opt/fermatai/.git") else "."

# HARDCODED YASAK — değiştirilemez
PROTECTED_BRANCHES = {"main", "master", "production", "develop", "release"}
BRANCH_PATTERN = re.compile(r"^bot/draft-\d{8}-\d+$")
DANGEROUS_GIT_FLAGS = {"--force", "-f", "--force-with-lease", "--force-if-includes",
                       "--mirror", "--all"}

# Daily quota
MAX_BRANCHES_PER_DAY = 10        # bot 1 günde max 10 branch açabilir
MAX_COMMITS_PER_BRANCH = 20      # bir branch'te max 20 commit


def _bot_signature() -> tuple[str, str]:
    """Commit author bilgileri — bot ile insan ayrımı."""
    return ("FermatAI Bot", "bot@fermatai.local")


def _commit_footer() -> str:
    """Her commit message'a eklenen Co-Author satırı."""
    return (
        "\n\n"
        "🤖 Generated by FermatAI Self-Dev (Evre 2.2)\n"
        "Co-Authored-By: FermatAI Bot <bot@fermatai.local>"
    )


async def _push_enabled() -> bool:
    """SELF_DEV_PUSH_ENABLED flag — default false."""
    try:
        from db_pool import db_fetchval
        v = await db_fetchval(
            "SELECT value FROM sistem_ayar WHERE key = 'SELF_DEV_PUSH_ENABLED'"
        )
        return (str(v or "false").lower() == "true")
    except Exception:
        return False


def _run_git(args: list[str], timeout: int = 30) -> tuple[int, str, str]:
    """git komutu çalıştır. (returncode, stdout, stderr)"""
    # Tehlikeli flag'leri filtrele
    for arg in args:
        if arg in DANGEROUS_GIT_FLAGS:
            return 99, "", f"YASAK FLAG: {arg}"
    cmd = ["git", "-C", REPO_PATH] + args
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                              timeout=timeout, errors="replace")
        return proc.returncode, proc.stdout.strip(), proc.stderr.strip()
    except subprocess.TimeoutExpired:
        return 98, "", "timeout"
    except Exception as e:
        return 97, "", str(e)


async def _check_daily_branch_quota(actor: str) -> tuple[bool, int]:
    """Bot bugün kaç branch açtı?"""
    from db_pool import db_fetchval
    try:
        n = await db_fetchval(
            """SELECT COUNT(*) FROM self_dev_audit
               WHERE actor_phone = $1
                 AND tool_name = 'create_draft_branch'
                 AND success = true
                 AND created_at > NOW() - INTERVAL '24 hours'""",
            actor,
        ) or 0
        return (int(n) < MAX_BRANCHES_PER_DAY), int(n)
    except Exception:
        return True, 0


async def _next_draft_branch_name(date_str: Optional[str] = None) -> str:
    """Bugün için sıradaki bot/draft-YYYYMMDD-N adı."""
    if not date_str:
        date_str = datetime.utcnow().strftime("%Y%m%d")
    rc, out, err = _run_git(["branch", "--list", f"bot/draft-{date_str}-*"])
    if rc == 0:
        existing = [b.strip().lstrip("* ") for b in out.splitlines() if b.strip()]
        nums = []
        for b in existing:
            m = re.match(rf"^bot/draft-{date_str}-(\d+)$", b)
            if m:
                nums.append(int(m.group(1)))
        next_num = (max(nums) + 1) if nums else 1
    else:
        next_num = 1
    return f"bot/draft-{date_str}-{next_num}"


# ─── ANA API ────────────────────────────────────────────────────────────────

async def create_draft_branch(_caller_phone: str = "") -> dict:
    """Yeni bot/draft-YYYYMMDD-N branch oluştur (lokal)."""
    from self_dev_tools import _is_pipeline_active, _audit
    if not await _is_pipeline_active():
        return {"error": "Self-dev pipeline kapali."}

    ok_quota, n = await _check_daily_branch_quota(_caller_phone)
    if not ok_quota:
        await _audit(_caller_phone, "create_draft_branch", {}, False,
                     blocked_by="daily_quota_exceeded")
        return {"error": f"Günlük branch kotası doldu ({n}/{MAX_BRANCHES_PER_DAY})"}

    branch_name = await _next_draft_branch_name()
    if not BRANCH_PATTERN.match(branch_name):
        await _audit(_caller_phone, "create_draft_branch", {"branch": branch_name},
                     False, blocked_by="invalid_branch_pattern")
        return {"error": "Branch isim regex'e uymadi"}

    # Mevcut branch'i kontrol et — main'de olmalıyız
    rc, current, _ = _run_git(["branch", "--show-current"])
    if rc != 0:
        return {"error": f"git branch --show-current basarisiz: {current}"}
    if current in PROTECTED_BRANCHES:
        # main'de olmalıyız zaten
        pass
    else:
        # Bot başka draft'ta kalmış — main'e dön
        rc2, _, err2 = _run_git(["checkout", "main"])
        if rc2 != 0:
            return {"error": f"main'e checkout basarisiz: {err2}"}

    # Yeni branch oluştur
    rc, out, err = _run_git(["checkout", "-b", branch_name])
    if rc != 0:
        await _audit(_caller_phone, "create_draft_branch", {"branch": branch_name},
                     False, error=err[:200])
        return {"error": f"Branch olusturulamadi: {err[:200]}"}

    await _audit(_caller_phone, "create_draft_branch",
                 {"branch": branch_name}, True, bytes_read=0)
    return {
        "ok": True,
        "branch": branch_name,
        "from": "main",
        "message": f"Yeni branch: {branch_name} (main'den ayrildi, lokal)",
    }


async def apply_diff_to_branch(brief_id: int, branch: Optional[str] = None,
                                 _caller_phone: str = "") -> dict:
    """Bir brief'in draft .diff'ini şu an bulunduğun branch'e UYGULA (gerçek dosyaya yazar).

    Args:
        brief_id: hangi brief'in diff'i
        branch: opsiyonel — branch adı (verilmezse mevcut branch kullanılır,
                ama mevcut branch BOT_PATTERN olmalı)

    GUVENLIK: branch ismi BRANCH_PATTERN'e uymalı, PROTECTED'da olmamalı.
    """
    from self_dev_tools import _is_pipeline_active, _audit
    if not await _is_pipeline_active():
        return {"error": "Self-dev pipeline kapali."}

    # Mevcut branch
    rc, current, _ = _run_git(["branch", "--show-current"])
    if rc != 0:
        return {"error": "Branch tespit edilemedi"}

    target_branch = (branch or current).strip()
    if target_branch in PROTECTED_BRANCHES:
        await _audit(_caller_phone, "apply_diff_to_branch",
                     {"brief_id": brief_id, "branch": target_branch},
                     False, blocked_by=f"protected_branch:{target_branch}")
        return {"error": f"PROTECTED branch'e uygulama YASAK: {target_branch}"}
    if not BRANCH_PATTERN.match(target_branch):
        await _audit(_caller_phone, "apply_diff_to_branch",
                     {"brief_id": brief_id, "branch": target_branch},
                     False, blocked_by="non_bot_branch")
        return {"error": f"Sadece bot/draft-* branch'lere apply yapilabilir. Mevcut: {target_branch}"}

    # Hedef branch'e checkout (zaten oradaysak no-op)
    if current != target_branch:
        rc, _, err = _run_git(["checkout", target_branch])
        if rc != 0:
            return {"error": f"checkout {target_branch} basarisiz: {err[:200]}"}

    # Draft .diff dosyasını bul
    from self_dev_apply import read_draft, DRAFTS_ROOT
    drafts = await read_draft(brief_id)
    if "error" in drafts:
        return {"error": drafts["error"]}
    diff_path = drafts.get("path")
    if not diff_path or not os.path.exists(diff_path):
        return {"error": "Draft dosyasi bulunamadi"}

    # git apply (sadece check first)
    rc, out, err = _run_git(["apply", "--check", diff_path])
    if rc != 0:
        await _audit(_caller_phone, "apply_diff_to_branch",
                     {"brief_id": brief_id, "branch": target_branch},
                     False, error=f"git apply --check fail: {err[:300]}")
        return {
            "error": "Diff uygulanabilir değil (git apply --check basarisiz)",
            "details": err[:500],
            "hint": "Diff path/satir numaralari yanlis olabilir. Brief'i yenile.",
        }

    # Gerçek apply
    rc, out, err = _run_git(["apply", diff_path])
    if rc != 0:
        await _audit(_caller_phone, "apply_diff_to_branch",
                     {"brief_id": brief_id, "branch": target_branch},
                     False, error=f"git apply fail: {err[:300]}")
        return {"error": f"git apply basarisiz: {err[:300]}"}

    # Status
    rc, status, _ = _run_git(["status", "--short"])
    changed_files = [ln.strip().split()[-1] for ln in status.splitlines() if ln.strip()]

    await _audit(_caller_phone, "apply_diff_to_branch",
                 {"brief_id": brief_id, "branch": target_branch,
                  "files": changed_files},
                 True, bytes_read=len(diff_path))
    return {
        "ok": True,
        "brief_id": brief_id,
        "branch": target_branch,
        "diff_path": diff_path,
        "changed_files": changed_files,
        "message": f"Diff {target_branch} branch'ine uygulandi. Dosyalar staged değil — commit yapilmali.",
    }


async def commit_on_branch(branch: str, message: str,
                            _caller_phone: str = "") -> dict:
    """bot/draft-* branch'e commit yap (Co-Author footer ile)."""
    from self_dev_tools import _is_pipeline_active, _audit
    if not await _is_pipeline_active():
        return {"error": "Self-dev pipeline kapali."}

    branch = (branch or "").strip()
    if branch in PROTECTED_BRANCHES:
        await _audit(_caller_phone, "commit_on_branch", {"branch": branch}, False,
                     blocked_by=f"protected:{branch}")
        return {"error": f"PROTECTED branch'e commit YASAK: {branch}"}
    if not BRANCH_PATTERN.match(branch):
        await _audit(_caller_phone, "commit_on_branch", {"branch": branch}, False,
                     blocked_by="non_bot_branch")
        return {"error": f"Sadece bot/draft-* branch'lere commit. Verilen: {branch}"}

    # Mevcut branch'te miyiz?
    rc, current, _ = _run_git(["branch", "--show-current"])
    if current != branch:
        rc, _, err = _run_git(["checkout", branch])
        if rc != 0:
            return {"error": f"checkout {branch}: {err[:200]}"}

    # Commit message + footer
    if len(message) < 5:
        return {"error": "Commit mesaji cok kisa (min 5 char)"}
    full_msg = message + _commit_footer()

    # Author + email zorla (system-wide config'i değiştirmeden)
    name, email = _bot_signature()
    rc, _, err = _run_git(["add", "-A"])
    if rc != 0:
        return {"error": f"git add -A: {err[:200]}"}

    rc, out, err = _run_git([
        "-c", f"user.name={name}",
        "-c", f"user.email={email}",
        "commit", "-m", full_msg,
    ], timeout=60)
    if rc != 0:
        await _audit(_caller_phone, "commit_on_branch", {"branch": branch}, False,
                     error=err[:200])
        return {"error": f"commit basarisiz: {err[:200]}"}

    # Son commit SHA
    rc2, sha, _ = _run_git(["rev-parse", "--short", "HEAD"])
    await _audit(_caller_phone, "commit_on_branch",
                 {"branch": branch, "sha": sha[:10]}, True,
                 bytes_read=len(full_msg))
    return {
        "ok": True,
        "branch": branch,
        "sha": sha[:10],
        "message_preview": message[:80],
    }


async def push_branch(branch: str, _caller_phone: str = "") -> dict:
    """bot/draft-* branch'i remote'a push et.

    SELF_DEV_PUSH_ENABLED flag false ise → graceful skip + lokal'de kalır.
    """
    from self_dev_tools import _is_pipeline_active, _audit
    if not await _is_pipeline_active():
        return {"error": "Self-dev pipeline kapali."}

    branch = (branch or "").strip()
    if branch in PROTECTED_BRANCHES:
        await _audit(_caller_phone, "push_branch", {"branch": branch}, False,
                     blocked_by=f"protected:{branch}")
        return {"error": f"YASAK: PROTECTED branch'e push: {branch}"}
    if not BRANCH_PATTERN.match(branch):
        await _audit(_caller_phone, "push_branch", {"branch": branch}, False,
                     blocked_by="non_bot_branch")
        return {"error": "Sadece bot/draft-* branch'ler push edilebilir."}

    # Push flag kontrolü
    if not await _push_enabled():
        await _audit(_caller_phone, "push_branch", {"branch": branch}, False,
                     blocked_by="push_disabled")
        return {
            "ok": False,
            "skipped": True,
            "reason": "push_disabled",
            "message": (
                "Push şu an KAPALI (SELF_DEV_PUSH_ENABLED=false). "
                "Branch lokal kaldı. Aktive etmek için: 'self dev push ac' "
                "+ VPS'te SSH key kurulumu gerek."
            ),
            "branch": branch,
        }

    # Push komutu — sadece bu branch, force YOK, tag YOK
    rc, out, err = _run_git(["push", "origin", branch], timeout=60)
    if rc != 0:
        # Network/auth hatasi gracefully handle
        await _audit(_caller_phone, "push_branch", {"branch": branch}, False,
                     error=err[:300])
        if "Permission denied" in err or "publickey" in err.lower():
            return {
                "error": "SSH yetkisi yok — VPS root SSH key'i GitHub'a kayıtlı değil",
                "details": err[:300],
                "hint": "Neo manuel kurulum gerek: ssh-keygen + GitHub'a deploy key ekle",
            }
        return {"error": f"Push basarisiz: {err[:300]}"}

    await _audit(_caller_phone, "push_branch",
                 {"branch": branch}, True, bytes_read=len(out))
    return {
        "ok": True,
        "branch": branch,
        "stdout": out[:300],
        "message": f"Branch {branch} GitHub'a push edildi.",
    }


async def list_bot_branches(local_only: bool = True) -> dict:
    """bot/draft-* branch'leri listele."""
    args = ["branch", "--list", "bot/draft-*"]
    if not local_only:
        args = ["branch", "-a", "--list", "bot/draft-*"]
    rc, out, _ = _run_git(args)
    if rc != 0:
        return {"branches": []}
    branches = []
    for ln in out.splitlines():
        ln = ln.strip()
        if not ln:
            continue
        is_current = ln.startswith("*")
        name = ln.lstrip("* ").strip()
        if BRANCH_PATTERN.match(name) or BRANCH_PATTERN.match(name.replace("remotes/origin/", "")):
            branches.append({"name": name, "current": is_current})
    return {"branches": branches, "count": len(branches)}


async def get_branch_status(branch: Optional[str] = None) -> dict:
    """Branch durumu — diff stats, son commit."""
    target = branch or ""
    if target and not BRANCH_PATTERN.match(target) and target not in PROTECTED_BRANCHES:
        return {"error": "Yalniz bot/draft-* veya main/master sorgulanabilir"}

    rc, current, _ = _run_git(["branch", "--show-current"])
    if rc != 0:
        return {"error": "branch --show-current fail"}

    target = target or current
    rc, log_out, _ = _run_git(["log", target, "-3",
                                "--pretty=format:%h | %ai | %s"])
    rc2, status_out, _ = _run_git(["status", "--short"])

    # main'den kac commit ahead?
    rc3, ahead_out, _ = _run_git(["rev-list", "--count", f"main..{target}"])
    ahead = int(ahead_out) if rc3 == 0 and ahead_out.isdigit() else 0

    return {
        "branch": target,
        "current": (target == current),
        "ahead_of_main": ahead,
        "uncommitted_changes": bool(status_out.strip()),
        "recent_commits": log_out.splitlines()[:3],
        "status_summary": status_out[:500],
    }


async def delete_local_branch(branch: str, _caller_phone: str = "") -> dict:
    """Lokal bot/draft-* branch sil. Remote'da varsa orada kalır."""
    from self_dev_tools import _is_pipeline_active, _audit
    if not await _is_pipeline_active():
        return {"error": "Self-dev pipeline kapali."}

    branch = (branch or "").strip()
    if branch in PROTECTED_BRANCHES:
        return {"error": f"YASAK: PROTECTED branch silinemez: {branch}"}
    if not BRANCH_PATTERN.match(branch):
        return {"error": "Sadece bot/draft-* branch silinebilir."}

    # Once main'e gec
    rc, current, _ = _run_git(["branch", "--show-current"])
    if current == branch:
        _run_git(["checkout", "main"])

    rc, out, err = _run_git(["branch", "-D", branch])
    if rc != 0:
        return {"error": f"Silme basarisiz: {err[:200]}"}

    await _audit(_caller_phone, "delete_local_branch", {"branch": branch}, True)
    return {"ok": True, "deleted": branch}


# ─── Tek-tıkla orkestasyon ──────────────────────────────────────────────────

async def draft_to_local_branch(brief_id: int, _caller_phone: str = "") -> dict:
    """Brief #N → yeni bot/draft branch + diff apply + commit (LOKAL).
    Push YAPILMAZ — Neo ayrıca 'push' komutu vermeli.

    Args:
        brief_id: Hangi brief'in diff'i
    """
    from self_dev_tools import _is_pipeline_active
    if not await _is_pipeline_active():
        return {"error": "Self-dev pipeline kapali."}

    # 1. Branch
    b = await create_draft_branch(_caller_phone=_caller_phone)
    if "error" in b:
        return {"step": "create_branch", **b}
    branch = b["branch"]

    # 2. Apply diff
    a = await apply_diff_to_branch(brief_id, branch, _caller_phone=_caller_phone)
    if "error" in a:
        # Cleanup: branch sil
        _run_git(["checkout", "main"])
        _run_git(["branch", "-D", branch])
        return {"step": "apply_diff", **a, "rolled_back": True}

    # 3. Commit
    from self_dev_brief import get_brief
    brief = await get_brief(brief_id)
    msg = f"draft: {brief.get('title', f'brief #{brief_id}')}"[:120]
    c = await commit_on_branch(branch, msg, _caller_phone=_caller_phone)
    if "error" in c:
        return {"step": "commit", **c, "branch_remained": branch}

    return {
        "ok": True,
        "branch": branch,
        "brief_id": brief_id,
        "sha": c.get("sha"),
        "changed_files": a.get("changed_files", []),
        "next_step": (
            "Lokal'de hazır. Push için 'self dev push ac' + 'draft #{0} push' yaz. "
            "İptal için 'draft #{0} branch sil'.".format(brief_id)
        ),
    }


# ─── Push flag toggle ───────────────────────────────────────────────────────

async def set_push_enabled(enabled: bool, by_phone: str = "") -> dict:
    """SELF_DEV_PUSH_ENABLED flag toggle."""
    from db_pool import get_pool
    try:
        pool = await get_pool()
        async with pool.acquire() as conn:
            await conn.execute(
                """INSERT INTO sistem_ayar (key, value, updated_at)
                   VALUES ('SELF_DEV_PUSH_ENABLED', $1, NOW())
                   ON CONFLICT (key) DO UPDATE SET value = $1, updated_at = NOW()""",
                "true" if enabled else "false",
            )
        from self_dev_tools import _audit
        await _audit(by_phone, "set_push_enabled", {"enabled": enabled}, True)
        return {
            "ok": True,
            "enabled": enabled,
            "message": (
                "Self-dev push AÇIK ✅ (Bot artık bot/draft-* branch'leri GitHub'a push edebilir)"
                if enabled else
                "Self-dev push KAPALI ⛔ (Bot lokal'de kalır)"
            ),
        }
    except Exception as e:
        return {"ok": False, "error": str(e)[:200]}


# ─── CLI test ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import asyncio
    import sys
    sys.stdout.reconfigure(encoding="utf-8")

    async def _test():
        print(f"REPO_PATH: {REPO_PATH}")
        print(f"PROTECTED: {PROTECTED_BRANCHES}")
        print(f"PATTERN: {BRANCH_PATTERN.pattern}")
        print(f"Push enabled: {await _push_enabled()}")
        print()

        # Mevcut branch
        rc, cur, _ = _run_git(["branch", "--show-current"])
        print(f"Current branch: {cur}")

        # bot/draft-* listesi
        bb = await list_bot_branches()
        print(f"Bot branches: {bb['count']}")
        for b in bb["branches"]:
            mark = " *" if b["current"] else "  "
            print(f"  {mark} {b['name']}")

        # Pattern test
        print()
        print("=== Branch pattern test ===")
        for b in [
            "bot/draft-20260430-1",
            "bot/draft-2026-1",
            "main",
            "feature/x",
            "bot/draft-20260430-99",
        ]:
            ok = bool(BRANCH_PATTERN.match(b))
            protected = b in PROTECTED_BRANCHES
            print(f"  [{('OK ' if ok else 'FAIL'):4s}] {b}{' (PROTECTED!)' if protected else ''}")

    asyncio.run(_test())
