"""
Pedagoji V2 — 76 Anekdot Seed Listesi (curated by Neo + Claude)
================================================================

Her seed:
  - kim: gerçek isim (halusilasyon önleme için curated)
  - kategori: 8 kategoriden biri (HAFIZA/MOTIVASYON/ODAK/STRES/DISIPLIN/KIMLIK/OGRENME/AZIM)
  - duygusal_hedef: detay (vazgecme, sinir, kadin, genc, ...)
  - core_facts: Cerebras üretiminde kullanılacak ÇEKİRDEK GERÇEKLER (halusilasyon engelleme)
  - kaynak: doğrulanmış kaynak
  - ders: opsiyonel ders bağı
  - etiketler: arama etiketleri

Bu seed Cerebras gpt-oss-120b'ye verilir → metin (200-300 char Türkçe) üretir.
Validation: çıktıda core_facts ile çelişki YASAK (regex check).
"""

ANEKDOT_SEED = [
    # ═══════════════════════════════════════════════════════════
    # KATEGORİ: AZIM (azim, başarısızlık, reddedilme — 14 anekdot)
    # ═══════════════════════════════════════════════════════════
    {
        "slug": "edison_10000_deneme",
        "kim": "Thomas Edison",
        "kategori": "AZIM",
        "duygusal_hedef": "basarisizlik,vazgecme,hata",
        "core_facts": "Edison ampul yaparken 10.000+ farklı malzeme denedi. Gazeteciye 'Ben başarısız olmadım, ampulün çalışmayacağı 10.000 yol keşfettim' dedi. 1879'da patent.",
        "kaynak": "Edison biyografi; Smithsonian Institution",
        "ders": "",
        "etiketler": "kesif,azim,basarisizlik,hata,abd",
    },
    {
        "slug": "michael_jordan_lise_disi",
        "kim": "Michael Jordan",
        "kategori": "AZIM",
        "duygusal_hedef": "basarisizlik,ret,azim",
        "core_facts": "10. sınıfta lise basketbol takımından kesildi (varsity'e alınmadı). Her gün 6'da salona gitti. NBA'de 6 şampiyonluk, 5 MVP. 'Kariyerimde 9000+ şut kaçırdım, bu yüzden başardım' dedi.",
        "kaynak": "For the Love of the Game (1998); ESPN biyografi",
        "ders": "",
        "etiketler": "spor,basarisizlik,azim,reddedilme,abd",
    },
    {
        "slug": "van_gogh_2_tablo",
        "kim": "Vincent van Gogh",
        "kategori": "AZIM",
        "duygusal_hedef": "reddedilme,toplum,kimlik",
        "core_facts": "Van Gogh hayattayken sadece 1-2 tablosunu sattı (kayıtlar tartışmalı). Kardeşi Theo'ya mektuplarında inancını yazdı. Bugün eserleri 100 milyon dolar+. 1890'da öldü.",
        "kaynak": "Van Gogh mektupları; Theo yazışmaları",
        "ders": "",
        "etiketler": "sanat,reddedilme,azim,gelecek,hollanda",
    },
    {
        "slug": "marie_curie_iki_nobel",
        "kim": "Marie Curie",
        "kategori": "AZIM",
        "duygusal_hedef": "azim,sartlar,kadin,bilim",
        "core_facts": "Polonya'dan Paris'e geldi. 1903 Fizik Nobel'i (Pierre + Becquerel ile), 1911 Kimya Nobel'i (yalnız). İki farklı bilim dalında Nobel — tarihte tek kadın. Radyum-Polonyum keşfetti.",
        "kaynak": "Marie Curie biyografi (Eve Curie 1937)",
        "ders": "",
        "etiketler": "nobel,fizik,kimya,kadin,azim,polonya",
    },
    {
        "slug": "jk_rowling_12_red",
        "kim": "J.K. Rowling",
        "kategori": "AZIM",
        "duygusal_hedef": "ret,azim,yazma,kadin",
        "core_facts": "Harry Potter ilk kitabı 12 yayınevi tarafından reddedildi (Bloomsbury kabul etti, 1997). O dönemde sosyal yardımla yaşıyordu, tek anneydi. Kitap 500M+ sattı, dünyanın en çok satan serisi.",
        "kaynak": "JK Rowling biyografi; The Telegraph röportaj",
        "ders": "edebiyat",
        "etiketler": "yazma,ret,azim,kadin,ingiltere",
    },
    {
        "slug": "stephen_king_carrie_30_red",
        "kim": "Stephen King",
        "kategori": "AZIM",
        "duygusal_hedef": "ret,yazma,azim",
        "core_facts": "İlk romanı Carrie 30+ kez reddedildi. Karısı çöp kutusundan müsveddeyi çıkarıp 'devam et' dedi. Doubleday yayınladı (1974). Bugün 350M+ kitap satışı, dünyanın en çok satan yaşayan yazarlarından.",
        "kaynak": "On Writing — Stephen King (2000); Doubleday arşivi",
        "ders": "edebiyat",
        "etiketler": "yazma,ret,azim,abd,korku",
    },
    {
        "slug": "frida_kahlo_kaza",
        "kim": "Frida Kahlo",
        "kategori": "AZIM",
        "duygusal_hedef": "engel,sanat,azim,kadin",
        "core_facts": "18 yaşında otobüs-tramvay kazasında omurilik kırıldı, 32+ ameliyat geçirdi. Yatağa bağlı kaldığında üzerine ayna astırıp kendi portresini çizdi. Dünyaca tanınmış meksikalı ressam. 1954'te öldü.",
        "kaynak": "Frida — Hayden Herrera (1983)",
        "ders": "",
        "etiketler": "sanat,kaza,azim,kadin,meksika",
    },
    {
        "slug": "stephen_hawking_als",
        "kim": "Stephen Hawking",
        "kategori": "AZIM",
        "duygusal_hedef": "engel,bilim,azim",
        "core_facts": "21 yaşında ALS (motor nöron) tanısı, 2-3 yıl ömür biçildi. 76 yaşında öldü (2018). Konuşma sentezleyici ile yazdı. 'Zamanın Kısa Tarihi' 25M+ sattı. Cambridge profesörü, Newton'un eski kürsüsü.",
        "kaynak": "Stephen Hawking biyografi; The Theory of Everything (2014)",
        "ders": "fizik",
        "etiketler": "bilim,engel,evren,azim,ingiltere",
    },
    {
        "slug": "abraham_lincoln_8_kez_kaybetti",
        "kim": "Abraham Lincoln",
        "kategori": "AZIM",
        "duygusal_hedef": "ret,azim,siyaset",
        "core_facts": "Senato adaylığı 1855 ve 1858'de kaybetti. Başkan yardımcılığı adaylığı 1856'da kaybetti. 1860'da ABD 16. Başkanı seçildi — köleliği kaldırdı. Bugün ABD tarihinin en saygın liderlerinden.",
        "kaynak": "Lincoln biyografi (Doris Kearns Goodwin)",
        "ders": "tarih",
        "etiketler": "siyaset,ret,azim,abd,baskanlik",
    },
    {
        "slug": "walt_disney_kovuldu",
        "kim": "Walt Disney",
        "kategori": "AZIM",
        "duygusal_hedef": "ret,is,azim",
        "core_facts": "Kansas City Star'dan 'yaratıcılık eksikliği' gerekçesiyle kovuldu (1919). İlk şirketi Laugh-O-Gram iflas etti. 1937'de 'Pamuk Prenses' ilk uzun animasyon. Bugün Disney $200B+ değerinde.",
        "kaynak": "Walt Disney — Neal Gabler (2006)",
        "ders": "",
        "etiketler": "yaraticilik,ret,azim,abd,sirket",
    },
    {
        "slug": "colonel_sanders_65_yas",
        "kim": "Colonel Sanders",
        "kategori": "AZIM",
        "duygusal_hedef": "yas,azim,gec_basari",
        "core_facts": "65 yaşında sosyal güvenlik çekiyle KFC tarifini satmaya başladı. 1009 restoran reddetti (efsane). 70'inde franchise patladı. Bugün KFC 25.000+ şubeli, dünya çapında. 90 yaşına kadar aktif kaldı.",
        "kaynak": "KFC kurum tarihçesi; Colonel Sanders biyografi",
        "ders": "",
        "etiketler": "yas,is,azim,abd,franchise",
    },
    {
        "slug": "oprah_isten_atildi",
        "kim": "Oprah Winfrey",
        "kategori": "AZIM",
        "duygusal_hedef": "ret,kadin,azim,medya",
        "core_facts": "İlk haber sunuculuğundan 'TV için uygun değil' denilerek atıldı (Baltimore, 1977). The Oprah Winfrey Show 25 yıl 1 numara oldu (1986-2011). İlk Afrikalı-Amerikan kadın milyarder.",
        "kaynak": "Oprah biyografi; Forbes",
        "ders": "",
        "etiketler": "ret,kadin,medya,azim,abd",
    },
    {
        "slug": "honda_ford_red",
        "kim": "Soichiro Honda",
        "kategori": "AZIM",
        "duygusal_hedef": "ret,azim,muhendis",
        "core_facts": "Toyota mühendislik işine başvurusu reddedildi (1938). Kendi piston atölyesini kurdu, savaşta yıkıldı, 2 kez yeniden başladı. Honda Motor 1948. Bugün dünyanın en büyük motor üreticisi.",
        "kaynak": "Honda biyografi; Honda corporate history",
        "ders": "",
        "etiketler": "muhendis,ret,azim,japonya",
    },
    {
        "slug": "ramanujan_kendi_kendine",
        "kim": "Srinivasa Ramanujan",
        "kategori": "AZIM",
        "duygusal_hedef": "kaynak_yokluk,bilim,deha,azim",
        "core_facts": "Hindistan'da fakir bir ailede doğdu (1887). Üniversiteye gidemedi. Tek bir matematik kitabıyla kendi kendine sayı teorisi keşfetti. G.H. Hardy onu Cambridge'e davet etti (1914). 32'sinde öldü, 3900+ teorem bıraktı, bazıları bugün hala çözülüyor.",
        "kaynak": "The Man Who Knew Infinity — Robert Kanigel (1991)",
        "ders": "matematik",
        "etiketler": "matematik,deha,hindistan,azim,kaynak_yokluk",
    },

    # ═══════════════════════════════════════════════════════════
    # KATEGORİ: MOTIVASYON (12 anekdot)
    # ═══════════════════════════════════════════════════════════
    {
        "slug": "aziz_sancar_harran",
        "kim": "Aziz Sancar",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "baslangic,vazgecme,sartlar",
        "core_facts": "1946 Mardin Savur'da 8 kardeşli çiftçi ailesinde doğdu. Köyde elektrik yoktu. İstanbul Tıp'ı kazandı, ABD'de DNA tamiri araştırdı. 2015 Kimya Nobel'i — DNA tamir mekanizması.",
        "kaynak": "Aziz Sancar Nobel Lecture 2015; biyografi",
        "ders": "",
        "etiketler": "turk,nobel,dna,azim,kokleri,saltik",
    },
    {
        "slug": "malala_15_vurdu",
        "kim": "Malala Yousafzai",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "sinir,egitim,kadin,cesaret",
        "core_facts": "15 yaşında Pakistan Swat Vadisi'nde okula gittiği için Taliban tarafından başından vuruldu (2012). Hayatta kaldı. 17 yaşında en genç Nobel Barış Ödülü sahibi (2014). Kız çocukları eğitimi savunucusu.",
        "kaynak": "I Am Malala — Malala Yousafzai (2013)",
        "ders": "",
        "etiketler": "nobel,egitim,kadin,azim,pakistan",
    },
    {
        "slug": "ibn_sina_18_hoca",
        "kim": "İbn-i Sina",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "genclik,hedef,zaman",
        "core_facts": "980 Buhara doğumlu. 10 yaşında Kuran'ı ezberledi, 16'da tıp kitapları okudu, 18'de tabip oldu. El-Kanun fi't-Tıb (Canon of Medicine) 6 asır Avrupa tıp fakültelerinde okutuldu. Modern tıbbın temel kitabı.",
        "kaynak": "İbn-i Sina — El-Kanun fi't-Tıb (1025)",
        "ders": "",
        "etiketler": "islam,tip,genc,hedef,buhara",
    },
    {
        "slug": "boyan_slat_18_okyanus",
        "kim": "Boyan Slat",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "genclik,hedef,cevre,proaktif",
        "core_facts": "Hollandalı, 16 yaşında Yunanistan'da scuba dalışta plastiğe rastladı. 18'inde TEDx konuşması yaptı (2012), 'The Ocean Cleanup' projesini kurdu. Şu an Pasifik Çöp Adası'ndan plastik topluyor — şirket $40M+ fonlu.",
        "kaynak": "TED talk 2012; The Ocean Cleanup org",
        "ders": "",
        "etiketler": "genc,cevre,girisim,hedef,hollanda",
    },
    {
        "slug": "hayao_miyazaki_90_yas",
        "kim": "Hayao Miyazaki",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "yas,sevgi,sanat,calisma",
        "core_facts": "1941 Tokyo doğumlu. Studio Ghibli'yi kurdu (1985). Nausicaä, Totoro, Spirited Away (Oscar 2003). 80+ yaşında hala film yapıyor — son filmi 'The Boy and the Heron' 2023 Oscar aldı.",
        "kaynak": "Studio Ghibli; The New Yorker röportaj",
        "ders": "",
        "etiketler": "sanat,yas,japonya,animasyon",
    },
    {
        "slug": "sabiha_gokcen_ilk_pilot",
        "kim": "Sabiha Gökçen",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "sinir,toplum_baskisi,cinsiyet",
        "core_facts": "1913 Bursa doğumlu, Atatürk'ün manevi kızı. 1937'de dünyanın ilk kadın savaş pilotu oldu. THK Türkkuşu'ndan eğitim aldı. İstanbul Sabiha Gökçen Havalimanı onun adıyla anılıyor.",
        "kaynak": "Sabiha Gökçen — Uçtum (1979 anı)",
        "ders": "",
        "etiketler": "turk,pilot,kadin,ilk,cesaret",
    },
    {
        "slug": "oktay_sinanoglu_25_yale",
        "kim": "Oktay Sinanoğlu",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "yas,bilim,turk,ozguven",
        "core_facts": "1935 Bari (İtalya) doğumlu Türk. 25 yaşında Yale Üniversitesi'nin en genç profesörü oldu (1960). Kuantum kimyasında çığır açtı — 'Çok Elektronlu Atom Teorisi' onun adını taşır. 2015'te öldü.",
        "kaynak": "Oktay Sinanoğlu biyografi; Yale arşivleri",
        "ders": "kimya",
        "etiketler": "turk,yale,kuantum,genc,ozguven",
    },
    {
        "slug": "canan_dagdeviren_mit",
        "kim": "Canan Dağdeviren",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "yas,kadin,bilim,turk",
        "core_facts": "1985 İstanbul doğumlu. ODTÜ Fizik Mühendisliği. Harvard PhD. 27 yaşında MIT'de kadrolu profesör oldu (2017) — MIT Conformable Decoders. Esnek elektronik + biyomedikal cihaz uzmanı. Time 100 (2019).",
        "kaynak": "MIT Media Lab; Time 100 — 2019",
        "ders": "fizik",
        "etiketler": "turk,mit,kadin,genc,bilim",
    },
    {
        "slug": "tu_youyou_artemisinin",
        "kim": "Tu Youyou",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "azim,kadin,bilim,kaynak_yokluk",
        "core_facts": "Çinli kimyager (1930-). Doktora yok, denizaşırı eğitim yok. 1972'de Artemisia bitkisinden artemisinin'i çıkardı — sıtma için en etkili tedavi. 2015 Tıp Nobel'i — Çin'in ilk bilim Nobel'i kazanan kadın.",
        "kaynak": "Nobel Lecture 2015; Tu Youyou biyografi",
        "ders": "kimya",
        "etiketler": "nobel,kadin,cin,bilim,sitma",
    },
    {
        "slug": "ada_lovelace_ilk_programci",
        "kim": "Ada Lovelace",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "kadin,vizyon,bilim,tarih",
        "core_facts": "1815-1852, Lord Byron'ın kızı. Charles Babbage'ın Analitik Makinesi için ilk algoritmayı yazdı (1843) — dünyanın ilk programcısı kabul edilir. 'Bir gün makineler müzik bestelerler' öngörüsü.",
        "kaynak": "Ada — The Enchantress of Numbers (Toole, 1992)",
        "ders": "matematik",
        "etiketler": "kadin,programlama,ilk,ingiltere,vizyon",
    },
    {
        "slug": "katherine_johnson_nasa",
        "kim": "Katherine Johnson",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "kadin,siyahi,bilim,sinir",
        "core_facts": "Afrikalı-Amerikalı matematikçi (1918-2020). NASA'da yörünge hesaplamalarını yaptı. Apollo 11 ay yolculuğunu, John Glenn'in dünya yörüngesini hesapladı. 'Hidden Figures' filmi (2016) onu anlatır. Başkanlık Madalyası 2015.",
        "kaynak": "Hidden Figures — Margot Lee Shetterly (2016)",
        "ders": "matematik",
        "etiketler": "kadin,siyahi,nasa,uzay,abd,sinir",
    },
    {
        "slug": "akut_nasuh_mahruki",
        "kim": "Nasuh Mahruki",
        "kategori": "MOTIVASYON",
        "duygusal_hedef": "hedef,etki,anlam,turk",
        "core_facts": "Türk dağcı. 1995'te ilk Türk Everest çıkışı. AKUT'u 1996'da 11 arkadaşla kurdu — 17 Ağustos 1999 depreminde 220+ can kurtardılar. AKUT bugün Türkiye'nin en saygın gönüllü kurtarma örgütü.",
        "kaynak": "Everest — Nasuh Mahruki (2003)",
        "ders": "",
        "etiketler": "turk,hedef,etki,dagci,deprem",
    },

    # ═══════════════════════════════════════════════════════════
    # KATEGORİ: HAFIZA (8 anekdot)
    # ═══════════════════════════════════════════════════════════
    {
        "slug": "harezmi_algoritma",
        "kim": "El-Harezmi",
        "kategori": "HAFIZA",
        "duygusal_hedef": "kimlik,ilham,tarih,matematik",
        "core_facts": "780-850 Bağdat. Kitab'ul-Cebr (cebir kelimesinin kökeni). Hindu-Arap rakamlarını Avrupa'ya taşıdı. 'Algoritma' kelimesi onun ismi 'Al-Khwarizmi'den Latince 'algorithmi' yapılmış.",
        "kaynak": "Robert of Chester — Algoritmi de numero Indorum",
        "ders": "matematik",
        "etiketler": "islam,matematik,cebir,tarih,bagdat",
    },
    {
        "slug": "ali_kuscu_astronomi",
        "kim": "Ali Kuşçu",
        "kategori": "HAFIZA",
        "duygusal_hedef": "ilham,bilim_tarihi,ozguven",
        "core_facts": "1403 Semerkant doğumlu Türk astronom. Ulu Bey'in rasathanesinde çalıştı. Fatih onu İstanbul'a getirdi (1473), Ayasofya başmüderrisi yaptı. Ay'ın enleminin değişimini hesapladı, modern öncesi astronominin önemli ismi.",
        "kaynak": "Aydın Sayılı — Türk Bilim Tarihi",
        "ders": "fizik",
        "etiketler": "turk,osmanli,astronomi,matematik,semerkant",
    },
    {
        "slug": "feynman_chicago_bilgi",
        "kim": "Richard Feynman",
        "kategori": "HAFIZA",
        "duygusal_hedef": "ogrenme,kavrama,bilim",
        "core_facts": "Nobelli fizikçi (1918-1988). Manhattan Project. 'Surely You're Joking' kitabında: bir konuyu öğrenmenin tek yolu — onu birine 12 yaşındaymış gibi anlatmak. Bu yöntemi 'Feynman Tekniği' olarak biliniyor.",
        "kaynak": "Surely You're Joking, Mr. Feynman! (1985)",
        "ders": "fizik",
        "etiketler": "fizik,nobel,ogrenme,teknik,abd",
    },
    {
        "slug": "yamanaka_ips",
        "kim": "Shinya Yamanaka",
        "kategori": "HAFIZA",
        "duygusal_hedef": "bilim,azim,kesif",
        "core_facts": "Japon hücre biyologu (1962-). Yetişkin hücreleri kök hücreye dönüştürmenin yolunu buldu (iPS hücreleri, 2006). 2012 Tıp Nobel'i. Kanser tedavisi ve organ üretimi için devrim.",
        "kaynak": "Nobel Lecture 2012; Yamanaka biyografi",
        "ders": "biyoloji",
        "etiketler": "nobel,japonya,hucre,kesif",
    },
    {
        "slug": "memory_champion_dominic",
        "kim": "Dominic O'Brien",
        "kategori": "HAFIZA",
        "duygusal_hedef": "hafiza,teknik,disiplin",
        "core_facts": "İngiliz hafıza şampiyonu. 8 kez Dünya Hafıza Şampiyonu. 54 desteyi (2808 kart) tek kez gördükten sonra hatırladı (2002 Guinness). Yöntemi: zihin sarayı (memory palace) — Antik Yunan tekniği.",
        "kaynak": "How to Develop a Brilliant Memory — D. O'Brien (1993)",
        "ders": "",
        "etiketler": "hafiza,teknik,sampiyon,ingiltere",
    },
    {
        "slug": "ebbinghaus_unutma_egrisi",
        "kim": "Hermann Ebbinghaus",
        "kategori": "HAFIZA",
        "duygusal_hedef": "bilim,hafiza,deney",
        "core_facts": "Alman psikolog (1850-1909). Kendisi üzerinde 11.000+ anlamsız hece denedi. Unutma eğrisini keşfetti (1885) — 1 saat sonra %60'ı unutuyor. Aralıklı tekrar (Spaced Repetition) onun deneyinden çıktı. Modern ezber tekniğinin temeli.",
        "kaynak": "Über das Gedächtnis — Ebbinghaus (1885)",
        "ders": "",
        "etiketler": "bilim,hafiza,deney,psikoloji,almanya",
    },
    {
        "slug": "kim_peek_rain_man",
        "kim": "Kim Peek",
        "kategori": "HAFIZA",
        "duygusal_hedef": "hafiza,fark,benzersiz",
        "core_facts": "ABD'li 'savant' (1951-2009). 12.000+ kitabı kelimesi kelimesine ezbere biliyordu. 'Yağmur Adam' filmi (Rain Man, 1988) ondan ilham aldı. Doğuştan beyin anomalisi vardı, ama olağanüstü hafıza.",
        "kaynak": "The Real Rain Man — Kim Peek biyografi",
        "ders": "",
        "etiketler": "hafiza,benzersiz,abd,savant",
    },
    {
        "slug": "augustus_caesar_isimler",
        "kim": "Julius Caesar",
        "kategori": "HAFIZA",
        "duygusal_hedef": "hafiza,liderlik,disiplin",
        "core_facts": "Romalı imparator (MÖ 100-44). Tarihçilerin yazdığına göre 30.000+ askerinin ismini, doğum yerini ezbere bilirdi. Cicero ona 'olağanüstü hafıza' dedi. Hafıza eğitimi (Loci yöntemi) Antik Roma'da yaygındı.",
        "kaynak": "Plutarkhos — Paralel Yaşamlar; Suetonius",
        "ders": "tarih",
        "etiketler": "tarih,roma,liderlik,hafiza",
    },

    # ═══════════════════════════════════════════════════════════
    # KATEGORİ: ODAK (6 anekdot)
    # ═══════════════════════════════════════════════════════════
    {
        "slug": "kobe_404_am",
        "kim": "Kobe Bryant",
        "kategori": "ODAK",
        "duygusal_hedef": "disiplin,motivasyon,zaman",
        "core_facts": "NBA basketbolcu (1978-2020). 5 NBA şampiyonluğu, 18 All-Star. Antrenmanlara 4'te başlardı — 'Mamba Mentality'. Rakipleri 8'de salondaysa kendisi onlardan 4 saat öndeydi.",
        "kaynak": "Mamba Mentality (2018); Lakers arşivleri",
        "ders": "",
        "etiketler": "spor,disiplin,sabah,azim,abd",
    },
    {
        "slug": "joe_hisaishi_5am",
        "kim": "Joe Hisaishi",
        "kategori": "ODAK",
        "duygusal_hedef": "disiplin,alişkanlik,ritual",
        "core_facts": "Studio Ghibli'nin film müziği bestecisi (1950-). Totoro, Spirited Away, Howl's Moving Castle bestecisi. 40+ yıldır her sabah 5'te masasına oturup 3-4 saat besteler. 'Yaratıcılık ilham değil alışkanlık.'",
        "kaynak": "Joe Hisaishi röportajları; NHK belgesel",
        "ders": "",
        "etiketler": "muzik,disiplin,ritual,japonya",
    },
    {
        "slug": "csikszentmihalyi_flow",
        "kim": "Mihaly Csíkszentmihályi",
        "kategori": "ODAK",
        "duygusal_hedef": "odak,akis,yontem,bilim",
        "core_facts": "Macar-Amerikalı psikolog (1934-2021). 'Flow' (Akış) kavramını keşfetti (1975). Sanatçılar, sporcular zorluk-yetenek dengesinde 'zamanın durduğunu' yaşar. Temel kitap: 'Flow' (1990).",
        "kaynak": "Flow: The Psychology of Optimal Experience (1990)",
        "ders": "",
        "etiketler": "odak,akis,bilim,psikoloji,macaristan",
    },
    {
        "slug": "cirillo_pomodoro",
        "kim": "Francesco Cirillo",
        "kategori": "ODAK",
        "duygusal_hedef": "odak,zaman,teknik",
        "core_facts": "İtalyan girişimci. 1980'lerde üniversite öğrencisiyken domates şeklinde mutfak zamanlayıcısı kullanarak 25/5 dakika çalışma tekniğini geliştirdi. 'Pomodoro' İtalyanca domates demek. Bugün dünya çapında uygulanan zaman yönetimi tekniği.",
        "kaynak": "The Pomodoro Technique — Cirillo (2006)",
        "ders": "",
        "etiketler": "odak,zaman,teknik,italya",
    },
    {
        "slug": "darwin_yuruyus_yolu",
        "kim": "Charles Darwin",
        "kategori": "ODAK",
        "duygusal_hedef": "odak,ritual,bilim",
        "core_facts": "İngiliz biyolog (1809-1882). Down House'da 'Sandwalk' adlı patikada her gün 3 kez yürüyerek düşünürdü. Türlerin Kökeni (1859) bu yürüyüşlerde şekillendi. Modern bilimde 'walking meditation' örneği.",
        "kaynak": "Darwin biyografi; Down House müzesi",
        "ders": "biyoloji",
        "etiketler": "bilim,evrim,ritual,ingiltere",
    },
    {
        "slug": "newton_plague_year",
        "kim": "Isaac Newton",
        "kategori": "ODAK",
        "duygusal_hedef": "odak,izolasyon,kesif",
        "core_facts": "İngiliz fizikçi (1642-1727). 1665-66 büyük veba salgını sırasında Cambridge kapandı. Newton 18 ay köyde izole kaldı — bu sürede kalkülüs, optik, yerçekimi yasalarını formüle etti. Kendi 'annus mirabilis' (mucize yıl) dedi.",
        "kaynak": "Newton biyografi (Westfall, 1980)",
        "ders": "fizik",
        "etiketler": "fizik,izolasyon,kesif,ingiltere",
    },

    # ═══════════════════════════════════════════════════════════
    # KATEGORİ: STRES (6 anekdot)
    # ═══════════════════════════════════════════════════════════
    {
        "slug": "michael_phelps_8_olimpiyat",
        "kim": "Michael Phelps",
        "kategori": "STRES",
        "duygusal_hedef": "kaygi,sampiyon,nefes,zihin",
        "core_facts": "ABD'li yüzücü, 23 olimpiyat altın madalyası — tarihteki en başarılı olimpiyat sporcusu. 2008 Pekin'de 8 altın. Anksiyete ve depresyon yaşadığını anlattı. Antrenörü Bob Bowman ile zihinsel hazırlık ve görselleştirme tekniği kullandı.",
        "kaynak": "The Weight of Gold (2020 belgesel); Phelps biyografi",
        "ders": "",
        "etiketler": "spor,olimpiyat,kaygi,zihin,abd",
    },
    {
        "slug": "obama_konsantrasyon_secim",
        "kim": "Barack Obama",
        "kategori": "STRES",
        "duygusal_hedef": "kaygi,karar,liderlik,nefes",
        "core_facts": "ABD 44. Başkanı (2009-2017). Yüksek baskı altında karar vermek için günlük rutin: kıyafet sayısını sınırlama (mavi/gri takım), düzenli egzersiz, müzik dinleme. 'Karar yorgunluğu'na karşı yaşam basitleştirme felsefesi.",
        "kaynak": "A Promised Land — Obama (2020); Vanity Fair röportaj",
        "ders": "",
        "etiketler": "siyaset,karar,zihin,abd,baskanlik",
    },
    {
        "slug": "simone_biles_olimpiyat_cekildi",
        "kim": "Simone Biles",
        "kategori": "STRES",
        "duygusal_hedef": "kaygi,zihin,kadin,cesaret",
        "core_facts": "ABD'li jimnastikçi (1997-), 7 olimpiyat madalyası. Tokyo 2020'de zihinsel sağlık nedeniyle takım finalinden çekildi — sporcu zihinsel sağlığı tartışmasını başlattı. 'Önce zihnim, sonra madalyalar' dedi. 2024 Paris'e dönüş, 3 altın daha.",
        "kaynak": "Simone Biles röportajları; Olympic.org",
        "ders": "",
        "etiketler": "spor,kadin,zihin,abd,olimpiyat",
    },
    {
        "slug": "kabat_zinn_mbsr",
        "kim": "Jon Kabat-Zinn",
        "kategori": "STRES",
        "duygusal_hedef": "stres,nefes,zihin,bilim",
        "core_facts": "ABD'li moleküler biyolog (1944-). 1979'da Massachusetts Tıp Fakültesi'nde MBSR (Mindfulness Based Stress Reduction) programını başlattı. Klinik araştırmalar mindfulness'ın stresi azalttığını kanıtladı. 35.000+ tıp kuruluşunda uygulanıyor.",
        "kaynak": "Full Catastrophe Living — Kabat-Zinn (1990)",
        "ders": "",
        "etiketler": "bilim,stres,mindfulness,abd,saglik",
    },
    {
        "slug": "viktor_frankl_anlam",
        "kim": "Viktor Frankl",
        "kategori": "STRES",
        "duygusal_hedef": "anlam,umut,direnis,trajik",
        "core_facts": "Avusturyalı nörolog ve psikiyatrist (1905-1997). Auschwitz dahil 4 toplama kampında hayatta kaldı. 'İnsanın Anlam Arayışı' (1946) kitabında: en zor şartlarda bile 'anlamı seçme özgürlüğü' var. Logoterapi'nin kurucusu.",
        "kaynak": "Man's Search for Meaning — V. Frankl (1946)",
        "ders": "",
        "etiketler": "psikoloji,anlam,direnis,avusturya",
    },
    {
        "slug": "hawkins_yerkes_dodson",
        "kim": "Yerkes & Dodson",
        "kategori": "STRES",
        "duygusal_hedef": "stres,bilim,deney,performans",
        "core_facts": "ABD'li psikologlar Robert Yerkes ve John Dillingham Dodson, 1908'de fareler üzerinde yaptıkları deneylerle 'Yerkes-Dodson Yasası'nı buldular: optimal performans için optimal düzeyde stres gerekir. Çok az = isteksizlik, çok fazla = donup kalma.",
        "kaynak": "Yerkes & Dodson — Journal of Comparative Neurology (1908)",
        "ders": "",
        "etiketler": "bilim,stres,performans,deney,abd",
    },

    # ═══════════════════════════════════════════════════════════
    # KATEGORİ: DISIPLIN (10 anekdot)
    # ═══════════════════════════════════════════════════════════
    {
        "slug": "franklin_13_erdem",
        "kim": "Benjamin Franklin",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "disiplin,sistem,plan",
        "core_facts": "ABD kurucu babalarından (1706-1790), bilim insanı, mucit. 20 yaşında 13 erdem belirledi: sükunet, çalışkanlık, dürüstlük, vb. Her hafta 1'ine odaklandı, 13 haftada tam döngü, yılda 4 tur. Otobiyografisinde 'mükemmel olamayız ama sistemli gelişiriz' dedi.",
        "kaynak": "Franklin Autobiography (1791)",
        "ders": "",
        "etiketler": "sistem,disiplin,plan,abd,erdem",
    },
    {
        "slug": "bts_10_yil_pratik",
        "kim": "BTS",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "disiplin,grup,asama,modern",
        "core_facts": "Güney Koreli K-pop grubu (debüt 2013). 7 üye debutten önce 2-3 yıl günde 12-14 saat çalıştılar. 2017'den itibaren küresel patlama. Billboard 100 numara 1, BB stadyumlarda konser veren ilk Koreli grup. Disiplin + grup uyumu örneği.",
        "kaynak": "Burn the Stage (2018 belgesel); Billboard",
        "ders": "",
        "etiketler": "muzik,disiplin,kore,modern,grup",
    },
    {
        "slug": "james_clear_atomic_habits",
        "kim": "James Clear",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "alışkanlik,kucuk,sistem",
        "core_facts": "ABD'li yazar (1986-). Lise beyzbol kazasında ciddi yaralandı, üniversitede beyzbola döndü. 'Atomic Habits' (2018) 15M+ kitap sattı. Tezi: %1 günlük gelişim 1 yılda 37x birikir. Habit stacking, environment design, identity-based habits.",
        "kaynak": "Atomic Habits — James Clear (2018)",
        "ders": "",
        "etiketler": "alışkanlik,sistem,abd,modern,kucuk",
    },
    {
        "slug": "wim_hof_buz_adam",
        "kim": "Wim Hof",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "disiplin,fiziksel,sinir,zihin",
        "core_facts": "Hollandalı 'Buz Adam' (1959-). Ekstremlere dayanıklılık rekorlarını kırdı: 26 dünya rekoru. Soğuk maruziyeti, nefes egzersizi, mental odakla bağışıklık sistemini bilinçli kontrol edebildiğini bilim insanlarına kanıtladı (Radboud Üniversitesi, 2014).",
        "kaynak": "The Wim Hof Method (2020)",
        "ders": "",
        "etiketler": "disiplin,fiziksel,bilim,hollanda",
    },
    {
        "slug": "haruki_murakami_kosu",
        "kim": "Haruki Murakami",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "disiplin,yazma,ritual",
        "core_facts": "Japon yazar (1949-). Her gün sabah 4'te kalkar, 5-6 saat yazar, 10 km koşar/yüzer. 30+ yıldır aynı ritüel. 'What I Talk About When I Talk About Running' (2007) bu disiplini anlatır. 'Norwegian Wood', '1Q84' yazarı.",
        "kaynak": "What I Talk About When I Talk About Running (2007)",
        "ders": "edebiyat",
        "etiketler": "yazma,disiplin,kosu,japonya",
    },
    {
        "slug": "kafka_gece_yazma",
        "kim": "Franz Kafka",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "disiplin,gece,yazma,fedakarlik",
        "core_facts": "Çek yazar (1883-1924). Gündüz sigorta şirketinde memurdu. Gece 22:30-3:00 arası yazardı. 'Dönüşüm' (1915), 'Dava', 'Şato' gece yazılmış. 41 yaşında veremden öldü, eserleri ölümünden sonra ünlendi.",
        "kaynak": "Kafka Günlükleri; Brod biyografi",
        "ders": "edebiyat",
        "etiketler": "yazma,disiplin,gece,cek,modern",
    },
    {
        "slug": "vince_lombardi_4_45_am",
        "kim": "Vince Lombardi",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "disiplin,liderlik,sabah",
        "core_facts": "Amerikan futbolu efsane antrenörü (1913-1970). Green Bay Packers'ı 5 NFL şampiyonluğu yaptı. Her sabah 4:45'te ofise gelirdi. Ünlü sözü: 'Mükemmellik bir alışkanlıktır, eylem değil.' (Aristoteles'ten esinlenerek.)",
        "kaynak": "When Pride Still Mattered — Maraniss (1999)",
        "ders": "",
        "etiketler": "spor,disiplin,liderlik,abd",
    },
    {
        "slug": "ronaldo_3_2_1",
        "kim": "Cristiano Ronaldo",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "disiplin,fiziksel,vucut,sampiyon",
        "core_facts": "Portekizli futbolcu (1985-). 5 Ballon d'Or. 38 yaşında dünya futbolunda en üst seviyede oynamaya devam ediyor — sebebi: günde 2-3 antrenman, 5 öğün, 8 saat uyku, alkol/sigara YOK, biyolojik yaşı 23 olarak ölçüldü.",
        "kaynak": "Ronaldo (2015 belgesel); Manchester United arşivleri",
        "ders": "",
        "etiketler": "spor,disiplin,fiziksel,portekiz",
    },
    {
        "slug": "stephen_king_2000_kelime",
        "kim": "Stephen King (yazma rutini)",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "disiplin,yazma,ritual,uretim",
        "core_facts": "ABD'li yazar (1947-). Her gün noel ve doğum günü dahil 2000 kelime yazma kuralı. 50+ yılda 60+ roman, 200+ öykü. 'On Writing' kitabında: 'İlham seni masada bulur — masada olmazsan bulunamazsın.'",
        "kaynak": "On Writing — Stephen King (2000)",
        "ders": "edebiyat",
        "etiketler": "yazma,disiplin,abd,uretim",
    },
    {
        "slug": "tolstoy_3000_kelime",
        "kim": "Lev Tolstoy",
        "kategori": "DISIPLIN",
        "duygusal_hedef": "disiplin,yazma,sabah",
        "core_facts": "Rus yazar (1828-1910). 'Savaş ve Barış' 1225 sayfa, 7 yılda yazdı (1865-1869). Sabah 9-2 arası kesintisiz yazardı. Karısı Sofya 7 kez Savaş ve Barış'ı temize çekti — Tolstoy'un sürekli düzeltmesi yüzünden.",
        "kaynak": "Tolstoy: A Russian Life — Bartlett (2010)",
        "ders": "edebiyat",
        "etiketler": "yazma,disiplin,sabah,rusya,klasik",
    },

    # ═══════════════════════════════════════════════════════════
    # KATEGORİ: KIMLIK (12 anekdot)
    # ═══════════════════════════════════════════════════════════
    {
        "slug": "ataturk_matematik_isim",
        "kim": "Mustafa Kemal",
        "kategori": "KIMLIK",
        "duygusal_hedef": "ilham,kimlik,hedef",
        "core_facts": "1881 Selanik. Manastır Askeri İdadisi'nde matematik öğretmeni Yüzbaşı Mustafa, küçük öğrencisine 'sen de Mustafa, ben de — birbirimize karışıyoruz. Senin için yakışan: Kemal — mükemmellik' dedi ve Kemal adını ekledi. Kurucu lider Türkiye Cumhuriyeti.",
        "kaynak": "Şevket Süreyya Aydemir — Tek Adam (1963)",
        "ders": "matematik",
        "etiketler": "turk,tarih,ataturk,matematik,kimlik",
    },
    {
        "slug": "cahit_arf_yurumek",
        "kim": "Cahit Arf",
        "kategori": "KIMLIK",
        "duygusal_hedef": "ilham,matematik_korkusu,kimlik",
        "core_facts": "1910-1997, ODTÜ Matematik bölümü kurucularından. 'Arf Değişmezi' onun adıyla anılır — dünya matematik literatürünün parçası. 'Bir matematik problemi çözmek bilmediğin bir tarafa yürümektir, ama en güzeli o yürüyüş' dedi.",
        "kaynak": "Cahit Arf biyografi; TÜBİTAK",
        "ders": "matematik",
        "etiketler": "turk,matematik,odtu,arf,kimlik",
    },
    {
        "slug": "yasargil_beyin_cerrahi",
        "kim": "Gazi Yaşargil",
        "kategori": "KIMLIK",
        "duygusal_hedef": "kimlik,bilim,turk,zirve",
        "core_facts": "1925 Lice doğumlu Türk beyin cerrahı. Mikrocerrahi tekniğini geliştirdi (1970'ler). 'Yüzyılın en iyi nörocerrahi' seçildi (Neurosurgery, 1999). Zürih ve Little Rock'ta 12.000+ ameliyat. 'Türk olduğumu hatırlamadan ameliyat yapmadım' dedi.",
        "kaynak": "Gazi Yaşargil biyografi; Neurosurgery (1999)",
        "ders": "biyoloji",
        "etiketler": "turk,tip,beyin,cerrahi,zirve",
    },
    {
        "slug": "maryam_mirzakhani_field",
        "kim": "Maryam Mirzakhani",
        "kategori": "KIMLIK",
        "duygusal_hedef": "kadin,matematik,iran,zirve,trajik",
        "core_facts": "İranlı matematikçi (1977-2017). Tahran'da büyüdü. Stanford profesörü. 2014'te Field Madalyası kazanan ilk kadın oldu (matematik Nobel'i). Dinamik sistemler ve hiperbolik geometri uzmanı. Meme kanserinden 40 yaşında öldü.",
        "kaynak": "Maryam Mirzakhani — Stanford anma",
        "ders": "matematik",
        "etiketler": "kadin,matematik,iran,nobel,zirve",
    },
    {
        "slug": "abdul_kalam_pilot_baskan",
        "kim": "A.P.J. Abdul Kalam",
        "kategori": "KIMLIK",
        "duygusal_hedef": "kimlik,koy,bilim,liderlik",
        "core_facts": "Hint roket bilimcisi (1931-2015). Tamil Nadu'da fakir aileyi gelecek vaadetmedi: pilot olamadı, mühendis oldu. ISRO'da Hindistan'ın ilk uydu fırlatma sistemini yönetti. 11. Hindistan Cumhurbaşkanı (2002-2007). 'Halkın Cumhurbaşkanı' lakabı.",
        "kaynak": "Wings of Fire — Abdul Kalam (1999)",
        "ders": "fizik",
        "etiketler": "hindistan,uzay,baskan,koy,kimlik",
    },
    {
        "slug": "obama_indonesia_havai",
        "kim": "Barack Obama",
        "kategori": "KIMLIK",
        "duygusal_hedef": "kimlik,kokenler,liderlik,gocmen",
        "core_facts": "44. ABD Başkanı (2009-2017). Hawaii'de doğdu, Kenyalı baba ve Kansas'lı anneden. Endonezya'da 4 yıl yaşadı. Harvard Hukuk. Columbia'da yan iş olarak başladı, ABD'nin ilk Afrikalı-Amerikan Başkanı oldu (2008). Kimlik karmaşası tartışıldı kitabında.",
        "kaynak": "Dreams from My Father — Obama (1995)",
        "ders": "",
        "etiketler": "siyaset,kimlik,gocmen,abd,baskan",
    },
    {
        "slug": "frankl_anlam_arayisi",
        "kim": "Viktor Frankl (anlam felsefesi)",
        "kategori": "KIMLIK",
        "duygusal_hedef": "anlam,kimlik,direnis,felsefe",
        "core_facts": "Viyanalı psikiyatrist (1905-1997). Naziler ailesini öldürdü, 4 toplama kampında 3 yıl. Auschwitz'te bir gözlemi: en kötü şartlarda 'neden yaşadığını' bilenler hayatta kaldı. Logoterapi (anlam terapisi) kurucusu. 'İnsan anlam arayan bir varlıktır.'",
        "kaynak": "Man's Search for Meaning (1946)",
        "ders": "",
        "etiketler": "psikoloji,anlam,kimlik,avusturya",
    },
    {
        "slug": "ramachandran_phantom_limb",
        "kim": "V.S. Ramachandran",
        "kategori": "KIMLIK",
        "duygusal_hedef": "bilim,beyin,kimlik,kesif",
        "core_facts": "Hint-Amerikalı nörobilimci (1951-). Hindistan Madras'ta büyüdü, Cambridge ve Caltech doktora. 'Phantom Limb' (hayalet uzuv) sendromuna ayna kutusu tedavisi geliştirdi. Beyin plastisitesini popülerleştirdi. Time '100 Etkili İnsan' (2011).",
        "kaynak": "Phantoms in the Brain — Ramachandran (1998)",
        "ders": "biyoloji",
        "etiketler": "bilim,beyin,hindistan,nobel_aday",
    },
    {
        "slug": "muhammad_ali_kimlik",
        "kim": "Muhammad Ali",
        "kategori": "KIMLIK",
        "duygusal_hedef": "kimlik,vicdan,prensip,siyahi",
        "core_facts": "ABD'li boksör (1942-2016). 1967'de Vietnam savaşına katılmayı reddetti — ahlaki/dinî gerekçe. Ağır siklet ünvanı elinden alındı, 3 yıl boks yapamadı, 1970'te döndü. 1996 Atlanta Olimpiyatları'nda Parkinson hastasıyken meşaleyi yaktı.",
        "kaynak": "King of the World — David Remnick (1998)",
        "ders": "",
        "etiketler": "spor,kimlik,vicdan,prensip,abd,siyahi",
    },
    {
        "slug": "rosa_parks_otobus",
        "kim": "Rosa Parks",
        "kategori": "KIMLIK",
        "duygusal_hedef": "kimlik,sinir,kadin,siyahi,cesaret",
        "core_facts": "ABD'li sivil haklar aktivisti (1913-2005). 1 Aralık 1955 Montgomery, Alabama'da otobüste beyaz adama yer vermeyi reddetti. Tutuklandı. Bu olay Montgomery Otobüs Boykotu'nu başlattı (Martin Luther King liderliğinde). Sivil haklar hareketinin başlangıç sembolü.",
        "kaynak": "Rosa Parks: My Story (1992); NAACP arşivleri",
        "ders": "tarih",
        "etiketler": "sivil_haklar,kadin,siyahi,abd,kimlik,cesaret",
    },
    {
        "slug": "mandela_27_yil",
        "kim": "Nelson Mandela",
        "kategori": "KIMLIK",
        "duygusal_hedef": "kimlik,direnis,liderlik,umut",
        "core_facts": "Güney Afrikalı politikacı (1918-2013). Apartheid karşıtı mücadele için 27 yıl hapsedildi (Robben Adası, 1962-1990). Çıktığında intikam değil uzlaşma seçti. 1994'te ülkenin ilk siyahi başkanı oldu. 1993 Nobel Barış Ödülü.",
        "kaynak": "Long Walk to Freedom — Mandela (1995)",
        "ders": "tarih",
        "etiketler": "siyaset,kimlik,direnis,gney_afrika,nobel",
    },
    {
        "slug": "gandhi_uzun_yuruyus",
        "kim": "Mahatma Gandhi",
        "kategori": "KIMLIK",
        "duygusal_hedef": "kimlik,liderlik,baris,direnis",
        "core_facts": "Hindistan'ın bağımsızlık lideri (1869-1948). Avukat. İngilizlerin tuz vergisine karşı 1930'da 24 günde 380 km yürüdü (Salt March). Şiddetsiz direniş (ahimsa) felsefesi. 1947'de Hindistan bağımsız oldu. 1948'de suikastla öldürüldü.",
        "kaynak": "Gandhi: My Experiments with Truth (otobiyografi, 1929)",
        "ders": "tarih",
        "etiketler": "siyaset,baris,hindistan,kimlik,direnis",
    },

    # ═══════════════════════════════════════════════════════════
    # KATEGORİ: OGRENME (8 anekdot)
    # ═══════════════════════════════════════════════════════════
    {
        "slug": "feynman_meron_ozelligi",
        "kim": "Richard Feynman (öğretme)",
        "kategori": "OGRENME",
        "duygusal_hedef": "ogrenme,teknik,kavrama",
        "core_facts": "Cornell ve Caltech profesörü (1918-1988). Lisans öğrencilerine fizik anlatırken karmaşık konuyu basit kelimelere indirgerdi. Lectures on Physics (1963) ders kitapları efsane oldu. 'Bir konuyu 12 yaşına anlatamıyorsan, anlamadın' yöntemi.",
        "kaynak": "The Feynman Lectures on Physics (1963)",
        "ders": "fizik",
        "etiketler": "fizik,nobel,ogretim,teknik",
    },
    {
        "slug": "einstein_kalkulus_15",
        "kim": "Albert Einstein",
        "kategori": "OGRENME",
        "duygusal_hedef": "ozguven,matematik_korkusu,efsane",
        "core_facts": "1879-1955. 'Einstein matematikte kötüydü' efsanesi YANLIŞ. 10 yaşında analitik geometri, 15'inde kalkülüs biliyordu. Efsane 1930'larda lise notları açıklanınca İsviçre 1=en yüksek not sistemi yanlış yorumlanarak doğdu.",
        "kaynak": "Walter Isaacson — Einstein: His Life and Universe (2007)",
        "ders": "matematik",
        "etiketler": "fizik,matematik,efsane,ozguven",
    },
    {
        "slug": "elon_musk_ogrenme",
        "kim": "Elon Musk",
        "kategori": "OGRENME",
        "duygusal_hedef": "ogrenme,sistem,plan",
        "core_facts": "Güney Afrika doğumlu girişimci (1971-). Tesla, SpaceX, Neuralink. 'Beyin ağaç gibidir, dalları olmadan yaprak yapamazsın — önce temel kavramı (ana dal), sonra detaylar (yapraklar)' yaklaşımı. Roket yapmayı ders kitaplarından kendi öğrendi.",
        "kaynak": "Elon Musk biyografi — Walter Isaacson (2023)",
        "ders": "",
        "etiketler": "girisim,ogrenme,sistem,modern",
    },
    {
        "slug": "polya_problem_cozme",
        "kim": "George Pólya",
        "kategori": "OGRENME",
        "duygusal_hedef": "ogrenme,matematik,teknik",
        "core_facts": "Macar matematikçi (1887-1985). Stanford profesörü. 'How to Solve It' (1945) — problem çözme heuristikleri. 4 adım: anla, plan yap, uygula, kontrol et. Kitap 1M+ sattı, hala matematik öğretiminde temel kaynak.",
        "kaynak": "How to Solve It — Pólya (1945)",
        "ders": "matematik",
        "etiketler": "matematik,teknik,ogrenme,macaristan",
    },
    {
        "slug": "vygotsky_zpd",
        "kim": "Lev Vygotsky",
        "kategori": "OGRENME",
        "duygusal_hedef": "ogrenme,bilim,sosyal,rehber",
        "core_facts": "Sovyet psikolog (1896-1934). 'Yakınsak Gelişim Alanı' (ZPD) kavramını geliştirdi (1920'ler). Öğrenme sosyaldir, rehber eşliğinde gerçek büyüme bölgesi vardır. 38 yaşında veremden öldü, eserleri Stalin döneminde yasaklandı, 1962'de keşfedildi.",
        "kaynak": "Thought and Language — Vygotsky (1934)",
        "ders": "",
        "etiketler": "psikoloji,ogrenme,bilim,rusya",
    },
    {
        "slug": "ericsson_10000_saat",
        "kim": "Anders Ericsson",
        "kategori": "OGRENME",
        "duygusal_hedef": "ogrenme,kalite,bilim",
        "core_facts": "İsveçli psikolog (1947-2020). '10.000 saat kuralı' onun araştırmasından kaynaklı (1993) — ama Gladwell yanlış basitleştirdi. Asıl tez: 'Deliberate Practice' (kasıtlı pratik). Spesifik zayıflığa odak + anında geri bildirim + konfor dışı zorluk.",
        "kaynak": "Peak: Secrets from the New Science of Expertise (2016)",
        "ders": "",
        "etiketler": "bilim,kalite,pratik,psikoloji,isvec",
    },
    {
        "slug": "doogie_howser_genc_yas",
        "kim": "Doogie Howser MD (gerçek hayat: Saul Barr)",
        "kategori": "OGRENME",
        "duygusal_hedef": "yas,akademi,erken",
        "core_facts": "ABD'li tıp doktoru ve öğrenci (1980-). 16 yaşında tıp fakültesini bitirdi, 18'inde lisanslı doktor oldu. ABD'nin en genç tıp doktorlarından. Disney film/dizi 'Doogie Howser' (1989) gerçek hayattaki örneklerden ilham aldı.",
        "kaynak": "Saul Barr biyografi; medical history archives",
        "ders": "biyoloji",
        "etiketler": "yas,tip,erken,abd,akademi",
    },
    {
        "slug": "khan_academy_salman",
        "kim": "Salman Khan",
        "kategori": "OGRENME",
        "duygusal_hedef": "ogrenme,paylasım,teknoloji,modern",
        "core_facts": "ABD'li girişimci ve eğitimci (1976-). MIT 3 lisans, Harvard MBA. 2008'de yeğenine matematik öğretmek için YouTube'a video yükledi. Khan Academy bugün dünyanın en büyük ücretsiz online okulu — 130+ ülkede milyonlarca öğrenci. NASA, Google, Bill Gates desteği.",
        "kaynak": "The One World Schoolhouse — Salman Khan (2012)",
        "ders": "",
        "etiketler": "egitim,teknoloji,paylasim,abd,modern",
    },
]


def get_kategori_dagilim() -> dict:
    """Kategori başına anekdot sayısını döndür (sanity check)."""
    from collections import Counter
    return dict(Counter(a["kategori"] for a in ANEKDOT_SEED))


if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding="utf-8")
    dist = get_kategori_dagilim()
    total = sum(dist.values())
    print(f"📊 Anekdot SEED dağılımı: {total} adet")
    print()
    for kat, cnt in sorted(dist.items(), key=lambda x: -x[1]):
        print(f"  {kat:12s} → {cnt:2d} anekdot")
    print()
    print(f"✅ Hedef: 76, Mevcut: {total}")
